---
# EDGEX NODE
- name: Add devices in edgex node metadata
  hosts: edgex_node
  become: true
  tasks:

    - name: Copy device files
      ansible.builtin.template:
          src: '{{ item[1] }}'
          dest: '/usr/local/edgex-runtime/{{ name }}.json'
      vars:
        address: "{{ hostvars[item[0]].internal_address }}"
        name: "{{ hostvars[item[0]].ansible_hostname }}"
      loop: "{{ groups['iot_nodes'] | product(query('fileglob', 'device_templates/*'))}}"

    - name: Get file contents
      ansible.builtin.slurp:
        path: '/usr/local/edgex-runtime/{{ name }}.json'
      vars:
        name: "{{ hostvars[item[0]].ansible_hostname }}"
      loop: "{{ groups['iot_nodes'] | product(query('fileglob', 'device_templates/*'))}}"
      register: files

    - name: Add edgex metadata
      ansible.builtin.command:
        cmd: >
          curl -X "POST" "http://localhost:59881/api/v3/device"
          -d '{{ item.content | b64decode | regex_replace( '\n','' )}}'
      loop: "{{ files.results }}"
      register: results

    - name: Print
      debug:
        var: results
