- name: Configure metadata on edge runtime
  hosts: edgex_node
  become: true
  tasks:
    # device profile metadata
    - name: Copy device profile files
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: /usr/local/edgex-runtime
      loop: "{{ query('fileglob', 'edgex_metadata/*') }}"

    - name: Add device profiles metadata
      ansible.builtin.command:
        cmd: >
          curl -X "POST" "http://localhost:59881/api/v3/deviceprofile/uploadfile"
          --form file='@"/usr/local/edgex-runtime/{{ item | basename }}"'
      loop: "{{ query('fileglob', 'edgex_metadata/*') }}"
      register: result
      changed_when:
        - '"201" in result.stdout '
      failed_when:
        - '"201" not in result.stdout and "409" not in result.stdout'

    # device metadata
    - name: Copy device files
      ansible.builtin.template:
          src: '{{ item[1] }}'
          dest: '/usr/local/edgex-runtime/{{ name }}.json'
      vars:
        address: "{{ hostvars[item[0]].internal_address }}"
        name: "{{ hostvars[item[0]].ansible_hostname }}"
      loop: "{{ groups['iot_nodes'] | product(query('fileglob', 'device_templates/*'))}}"

    - name: Get file contents
      ansible.builtin.slurp:
        path: '/usr/local/edgex-runtime/{{ name }}.json'
      vars:
        name: "{{ hostvars[item[0]].ansible_hostname }}"
      loop: "{{ groups['iot_nodes'] | product(query('fileglob', 'device_templates/*'))}}"
      register: files

    - name: Add device metadata
      ansible.builtin.command:
        cmd: >
          curl -X "POST" "http://localhost:59881/api/v3/device"
          -d '{{ item.content | b64decode | regex_replace( '\n','' )}}'
      loop: "{{ files.results }}"
      register: results
      changed_when:
        - '"201" in results.stdout '
      failed_when:
        - '"201" not in results.stdout and "409" not in results.stdout'
