---
# EDGEX NODE
- name: Install Docker
  hosts: edgex_node
  become: true
  pre_tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: false
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present

  tasks:

    - name: create working directory
      ansible.builtin.file:
        path: /usr/local/edgex-runtime
        state: directory
        mode: '755'

    - name: Download docker compose file for edgex runtime
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /usr/local/edgex-runtime/docker-compose.yml
        mode: '644'

    - name: start edgex runtime
      community.docker.docker_compose_v2:
        project_src: /usr/local/edgex-runtime
        state: present

    - name: Copy metadata files
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: /usr/local/edgex-runtime
      loop: "{{ query('fileglob', 'edgex_metadata/*') }}"

    - name: Add edgex metadata
    #delegate_to: localhost
    #become: false
      ansible.builtin.command:
        cmd: >
          curl -X "POST" "http://localhost:59881/api/v3/deviceprofile/uploadfile"
          --form file='@"/usr/local/edgex-runtime/{{ item | basename }}"'
      loop: "{{ query('fileglob', 'edgex_metadata/*') }}"
      register: result

 # IOT DEVICES
- name: Provision iot devices
  hosts: iot_nodes
  become: true
  tasks:

    - name: Install snmp agent
      ansible.builtin.apt:
        name: snmpd
        state: present
        update_cache: true

    - name: enable agent on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/snmp/snmpd.conf
        regex: 'agentaddress  .*'
        line: 'agentaddress  127.0.0.1,[::1]'
        state: present

    - name: Restart snmp agent
      ansible.builtin.service:
        name: snmpd
        state: restarted
